version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - yolo-service

  yolo-service:
    build: ./ai
    container_name: yolo-service
    runtime: nvidia # Use NVIDIA runtime for GPU access
    shm_size: '2gb'
    tty: true # Keep the container running for interactive use
    volumes:
    - .:/app # Mount the entire project directory for easy access to code and datasets 
    working_dir: /app
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
